### ISSUE TITLE
[FEAT]: Implement Google OAuth2.0

### ISSUE THREAD

**Issue by Khingz** [hngprojects/hng_boilerplate_expressjs#150]
### **Description**
Implement Google OAuth2.0 authentication in our application using the passportjs library. The authenticated user's data should be saved in our database. This feature will allow users to log in using their Google accounts, improving the user experience and security.

### Acceptance Criteria
- [ ] User can signin using their google account
- [ ] Save authenticated user data in the database
- [ ] Issue JWT upon successful authentication
- [ ] Protect route using JWT
- [ ] Provide proper error handling for the implemented feature

### Purpose
To enhance user experience by providing an additional authentication method through Google, making it easier for users to log in.

### Tasks
* Setup google API credentails
* Install necessary packages 
* Configure Google OAuth2.0 Client
* Implement authentication route
        * Get route `GET /api/v1/auth/google` to initiate the Google authentication process.
        * An internal callback route `GET /api/v1/auth/callback/google` to handle the OAuth2.0 callback from Google.
* Implement code to exchange the authorization code for tokens using `oAuth2Client.getToken`.
* Implement code to verify the ID token using `oAuth2Client.verifyIdToken` and extract the data from the token payload.
        * token payload
    ```javascript
        {
            "id": "12je23u-d2i9j2in-f4imi91jf98-49junu8d3un8dnuei",
            "email": "johnson.oragui@gmail.com",
            "verified_email": true,
            "name": "Johnson Oragui",
            "given_name": "Johnson",
            "family_name": "Oragui",
            "picture": "https://lh3.googleusercontent.com/a-/AOh14Gh2G_YHMAI",
            "locale": "en"
        }
    ```
        
* Create a new user if not exist or update existing user from the token payload
* Create a JWT containing user information and send it back to the client.
        * Successful Response
    ```javascript
        {
            "status": "success",
            "message": "User successfully authenticated",
            "access_token": "ey1093e1398jd98913d09209048...",
            "user": {
                "id": "iomdi2j982j-309vkq309-3qrvq3v-34ijmqi9i3uvn3",
                "email": "johnson.oragui@gmail.com",
                "first_name": "Johnson Oragui",
                "last_name": "Johnson",
            }
        }
    ```
### Error Handling
**Error Response**
    * Define error responses for common failure scenarios.
    * Example: If server fails to authenticate user, return a 500 status code with an error message
```javascript
    {
        "status": "unsuccessful",
        "status_code": 500,
        "message": "Failed to authenticate user."
    }
```

### Database Schema
The user schema will include a google_id field that will be provided by google. This ID ensures that each user has a unique identifier across the application system
```
    Table users {
        id integer [primary key]
        identifier uuid
        first_name varchar
        last_name varchar
        email varchar
        password varchar [null]
        google_id varchar [null]
        created_at timestamp
        updated_at timestamp
    }
```

### Performance and Security
* Analyze and optimize the API to address any potential performance issues.
* Ensure security by implementing data sanitization measures.

### Testing
* Write unit tests and integration tests for all new endpoints and functionalities.
