### ISSUE TITLE
[FEAT]: Authentication: Email Verification Endpoint

### ISSUE THREAD

**Issue by PreciousIfeaka** [hngprojects/hng_boilerplate_expressjs#154]
## Description
Implement a middleware function to verify email addresses during the authentication process using a token and OTP. This middleware ensures that only users with verified email addresses can access certain routes. This is integrated into the authentication system, hence, improving security.

## Purpose
To enhance authentication security and integrity by ensuring that only users with verified email addresses can access protected routes.

## Objective
Enhance the email verification process by:
-    The middleware should verify the user's email during the authentication process.
-    Ensuring the middleware is easily configurable and can be applied to specific routes.
-    Improving error handling and providing clear messages.

## Acceptance Criteria
- [ ] User's email is verified during the authentication process.
- [ ] If the email is verified, allow the request to proceed.
- [ ] If the email is not verified, respond with an appropriate error message and status code.
- [ ] Proper error handling and clear error messages are provided.

## Tasks
- [ ] Create middleware function that verifies the user's email using a token and OTP.
- [ ] Configure middleware to protect authentication routes based on email verification status.
- [ ] Provide proper error handling and clear error messages.

## Successful Response
- The system returns the `200 "success"` status code if the email verification is successful.
```json
{
  "status": "success",
  "message": "Email successfully verified",
  "status_code": 200
}
```

## Error Handling:
- If the user does not exist, the system returns the `404 "User not found"` error
```json
{
    "status": "unsuccessful",
    "status_code": 404,
    "message": "User not found"
}
```
- The system returns `400 "Invalid OTP"` error if the OTP is invalid
```json
{
    "status": "unsucessful",
    "status_code": 400,
    "message": "Invalid OTP"
}
```

- The system returns `400 "Verification token has expired"` error message if the token is invalid
```json
{
    "status": "unsucessful",
    "status_code": 400,
    "message": "Verification token has expired"
}
```

### unit tests
- User with a verified email is allowed to proceed.
- User with an unverified email is denied access.
- Proper response, error message and status code are returned when access is granted or denied.
