### ISSUE TITLE
[FEAT] ALLOW A USER GET A SINGLE PRODUCT

### ISSUE THREAD

**Issue by staq001** [hngprojects/hng_boilerplate_expressjs#165]
### Description
> Develop API endpoint that retrieves information about a single product. The response includes product details such as ID, name, description, price, and availability.

### Acceptance Criteria

- The endpoint `/api/v1/products/{product-id}` is accessible via a GET request.
- When a valid `product-id` is provided, the endpoint returns a `200` OK status.
- When an invalid `product-id` format is provided, the endpoint returns a `400` Bad Request status.
- On an invalid request, the response body contains an error message indicating the invalid product ID format.
- When a `product-id` that does not exist is provided, the endpoint returns a `404 `Not Found status.
- For a product that does not exist, the response body contains an error message indicating that the product was not found.
- If an unexpected server error occurs, the endpoint returns a 500 Internal Server Error status.
- The response body of an error 500 response contains an error message indicating that an unexpected error occurred.
- Ensure that all unit and integration tests for the fetch single product endpoint are comprehensive, and verify the functionality correctly.

### Purpose
- This provides a backend service that allows fetching detailed information on selected/specific product

### Tasks
- [ ]   Create an endpoint `/api/v1/products/{product-id}` to fetch details of a single product.
- [ ]  Implement server-side logic to handle successful and failed product retrieval requests.
- [ ]  Implement logging for errors and product retrieval attempts.
- [ ]  Write unit tests for the fetch single product endpoint.

### Expected Outcome
- API endpoint that returns detailed information on specific product

### Successful Response
- **Code: 200 OK**
- **Content**
```
{
 "product": {
   "id": "string",
   "name": "string",
   "description": "string",
   "price": "number",
   "available": "boolean",
   "category": "string",
   "created_at": "string",
   "updated_at": "string"
 }
}
```
### **Error Responses**
- **Code: 400 Bad Request**
- **Content**
```
{
  "error": "Invalid product ID"
}
```
- **Code: 404 NOT FOUND**
- **Content**

```
{
  "error": "Product not found"
}
```
- **Code: 500 INTERNAL SERVER ERROR**
- **Content**

```
{
  "error": "An unexpected error occurred"
}
```
### **Example Request**
- **Fetch product by ID**

```curl -X GET "https:/<base-url>/api/v1/products/12345```

**Comment by davieoba** [comment]
@AdeGneus @incredible-phoenix246, I am working on the api routes for products and in all the requests I have handled only this api route is not following the same response error code as the others. For example,
```js
status_code: 401,
status: "unsuccessful",
message: "Unauthorized"
```

Should this be ignored or we should maintain consistency?

**Comment by incredible-phoenix246** [comment]
Yes

**Comment by davieoba** [comment]
Okay.
