### ISSUE TITLE
[FIX] Fix and Enhance Flutterwave Payment Implementation

### ISSUE THREAD

**Issue by Uzo-Felix** [hngprojects/hng_boilerplate_expressjs#335]
### Description
We need to fix and enhance the existing Flutterwave payment implementation to ensure it's working correctly and follows best practices. The current implementation has some issues that need to be addressed.

### Acceptance Criteria

- [ ] Update the API endpoint to `/api/v1/payments/flutterwave/initiate` for consistency with the existing code.
- [ ] Ensure the payment initiation endpoint is properly secured with authentication middleware.
- [ ] Implement proper error handling and validation for the payment initiation process.
- [ ] Update the payment verification process to correctly handle the Flutterwave response.
- [ ] Implement proper error handling for the verification process.
- [ ] Ensure sensitive data (like card details) is handled securely.
- [ ] Update the database operations to correctly reflect the payment status.
- [ ] Implement proper logging for payment operations.
- [ ] Update the Swagger documentation to accurately reflect the implemented endpoints and their behavior.

### Tasks

1. Update `PaymentController.ts`:
   - [ ] Improve error handling in `initiatePayment` method.
   - [ ] Update `verifyPayment` method to correctly handle Flutterwave's response.
   - [ ] Ensure proper status updates in the database after verification.

2. Update `flutter.service.ts`:
   - [ ] Review and update the `initializePayment` function to ensure it's correctly handling all required fields.
   - [ ] Update the `verifyPayment` function to correctly interpret Flutterwave's response.
   - [ ] Implement proper error handling and logging.

3. Update `payment.ts` (router):
   - [ ] Ensure all routes are properly protected with authentication middleware.

4. General improvements:
   - [ ] Implement input validation for all user-provided data.
   - [ ] Ensure sensitive data (like card details) is not logged or stored unnecessarily.
   - [ ] Update Swagger documentation to accurately reflect the current implementation.

#### POST /api/v1/payments/flutterwave/initiate

Request Body:
```json
{
  "card_number": "string",
  "cvv": "string",
  "expiry_month": "string",
  "expiry_year": "string",
  "email": "string",
  "fullname": "string",
  "phone_number": "string",
  "currency": "string",
  "amount": "number",
  "payer_id": "string",
  "payer_type": "user" | "organization"
}
```

Success Response:
```json
{
  "status": "success",
  "message": "Payment initiated successfully",
  "data": {
    // Flutterwave response data
  }
}
```

#### GET /api/v1/payments/flutterwave/verify/{transactionId}

Success Response:
```json
{
  "status": "success",
  "message": "Payment verified successfully",
  "data": {
    // Verification details
  }
}
```

### Error Handling

Implement consistent error responses for various scenarios:

- 400 Bad Request: For validation errors
- 401 Unauthorized: For authentication errors
- 403 Forbidden: For authorization errors
- 500 Internal Server Error: For server-side errors

### Testing Requirements

- [ ] Write unit tests for the `initializePayment` and `verifyPayment` functions in `flutter.service.ts`.
- [ ] Write integration tests for the payment initiation and verification processes.
- [ ] Test error scenarios and ensure proper error handling.

### Security Considerations

- [ ] Ensure all sensitive data (like API keys and card details) are properly secured and not exposed in logs or error messages.
- [ ] Implement rate limiting to prevent abuse of the payment endpoints.
- [ ] Use HTTPS for all API communications.

This revised issue focuses on fixing and enhancing the existing Flutterwave implementation based on the code you've provided, addressing potential issues and improving the overall reliability and security of the payment process.
