### ISSUE TITLE
[Feat]: Send OTP

### ISSUE THREAD

**Issue by Nainah23** [hngprojects/hng_boilerplate_expressjs#458]
## Description

Implement a feature to send an OTP to the user for the endpoint `api/v1/auth/request/token`. Before sending a new OTP, the system should check if an existing OTP for the user already exists. If an existing OTP is found, it should be deleted before a new OTP is generated and sent.

## Acceptance Criteria

- The endpoint must return a 422 error for missing or invalid input with an appropriate error message.
- A 401 status code should be returned for invalid credentials with an appropriate error message.
- A successful request should return a 200 response with a success message.
- OTP should be transmitted securely to the user via email or SMS.
- Once validation checks are passed, an OTP is generated for the user and sent as part of the response payload.

## Expected Outcome

- The user should receive the OTP successfully or receive an error message if unsuccessful.
- Users are informed of OTP request activity.

## Requirements

Corresponding database fields for:
- Email Address
- OTP Token
- OTP Expiry Time

### Request

```http
POST /api/v1/auth/request/token
Content-Type: application/json

{
  "email": "user@example.com"
}
```

### Successful Response

```json
{
  "message": "OTP has been sent to your email."
}
```

#### Missing or Invalid Input

```json
{
  "message": "Invalid input.",
  "error": "Email is required.",
  "status_code": 422
}
```

#### Invalid Credentials

```json
{
  "message": "User not found.",
  "error": "No user exists with the provided email.",
  "status_code": 401
}
```

## Implementation Steps

1. **New Method in AuthService**:
    - Create a new method `requestOtp` in `authservice.ts` that handles the logic for checking existing OTPs, deleting them if found, generating a new OTP, and sending it to the user.

2. **Modify OTP Service**:
    - Update the OTP service to include a method for checking existing OTPs and deleting them.

3. **Update Routes**:
    - Add a new route in the authentication routes file to handle requests to `api/v1/auth/request/token`.

4. **Unit Tests**:
    - Write unit tests for the new method to ensure it behaves as expected, including scenarios where an existing OTP is found and deleted, and where no existing OTP is found.

## Check List

- [ ] Endpoint `api/v1/auth/request/token` created
- [ ] Logic to check for existing OTP and delete if found
- [ ] Logic to generate and send new OTP
- [ ] Appropriate success and error responses
- [ ] Unit tests for new functionality
```
